### PR TITLE
Speed up x2.7 using multiprocessing

### PR DESCRIPTION
**Pull request by hugovk**
I timed the change in PR https://github.com/janesolomon/twitter_search/pull/2 on a subset of one day's tweets, and the PR was slightly quicker (15.69 min) than the original (15.76 min), and the other suggested possible refactor was slightly slower (15.79 min), but just by a couple of minutes when scaled up to a whole month's worth (31\*15.76 - 31\*15.69 = 2.17min).

But we can do better! The original code is sequential: one file zipped file of tweets is opened, processed, results are stored, and then we move on to the next file. This doesn't make full use of the computer's often multiple CPUs.

---

Multiprocessing
---

Instead, we can use Python's `multiprocessing` library. For this, we create a new worker function and move into here the main bit of code that processes a file of zipped tweets. 

We then create a `Pool` that represents a pool of worker processes. The maximum that can run at any one time is set as the number of CPUs on the computer (`multiprocessing.cpu_count()`, 4 on this computer). We tell that to run the worker function on each of the filenames we have. It then runs each worker in its own process (up to that maximum). When one finishes, it'll take another from the pool.

```python
pool = multiprocessing.Pool(number_of_processes)
results = pool.map(worker, files)
```

Because of the way the multiprocessing works, the results can't be put in big global lists and dictionaries directly by the worker. So it pops them into its own dict and returns them. Then at the end, these are combined together. 

Also, the multiprocessing means that zip files are not necessarily processed in the same order, and the order of results in the CSVs may be a bit different, but that doesn't really matter: the totals and values are the same.

(For this, I also copied full_search_v1.ipynb into full_search.py to run it from the command line like `python full_search.py` because I'm not familiar with Jupyter Notebook. I've not deleted full_search_v1.ipynb in case there's something it was doing which is missed in the script, but in general it's better to avoid duplicating things.)

---

Results
---

Here's the CPU usage of the original sequential code (on Windows 7 with four CPUs/16 GB RAM):

CPUs at 30%

Here's how it looks with multiprocessing:

CPUs at 100%

Here's how long the original took (running on the full January 2017 tweet archive):
```
Elapsed Time    : 490.88 min=================================]  99.9% ...Searching Day 31, Hour 23
Total Tweets    : 112407850
Total Matches   : 22922
Total w/ Before : 482
Total w/ After  : 0
```

And with multiprocessing:
```
Elapsed Time    : 197.60 min=================================]  99.9% ...Searching Day 31, Hour 23
Total Tweets    : 112407850
Total Matches   : 22922
Total w/ Before : 482
Total w/ After  : 0
```

490.88 min -> 197.60 min == 8h 11m -> 3h 18m

That's about 2.5 times faster!

---

Other notes
---

The progress bar isn't as smooth. Before it would update with each file, now it only updates after processing each hour's worth of tweets. I expect this can be improved, but it's not a big worry.

Maybe this could be sped up a little more. I think those dips in the CPU chart are when it's finished one hour and moving onto the next, which involves the pool emptying completely before we fill it up with the next hours. Perhaps it'd be a bit faster if we made one big `files` list for all days and hours, and then fed that into the pool. I might test this out.

### CODE REVIEW

**Comment by hugovk** [comment]
I tested collecting together all of the files first, before starting the multiprocessing, and it shaved off another 13 minutes which I think is worthwhile, so the last commit adds this.

This would have made the progress bar less useful, so I've replaced it with one from the `tqdm` library which shows a progress bar according to the number of files processed. You can install it with `pip install tqdm`. I've also added a requirements.txt file, which is conventionally used by Python projects to list required libraries, and they can all be installed with `pip install -r requirements.txt`.


Results
---

The CPU chart shows no little dips:

100% CPU with no little dips

```
100%|##########################################################################| 43800/43800 [3:04:36<00:00,  3.95files/s]
Elapsed Time    : 184.60 min
Total Tweets    : 112407850
Total Matches   : 22922
Total w/ Before : 482
Total w/ After  : 0
```

490.88 min -> 197.60 min -> 184.60 min == 8h 11m -> 3h 18m -> 3h 5m

That's about 2.7 times faster!

**Comment by janesolomon** [comment]
Thanks for taking the time to make these suggestions. I'm excited to try them out.

I didn't have time to closely look over this yet, but I noticed that the total count for the after gun position is 0 in this, and I know that can't be the case.

**Comment by hugovk** [comment]
Odd that I got zero for the original code too, but I'll have another look in case I made a mistake.

**Comment by jzmnd** [comment]
Hi, I just ran your MP code on our dataset for 1 day (Aug 2016) with 8 cpu cores and 2.5 GB per core and got the expected results:

Without MP:
```
Elapsed Time    : 18.18 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 929
Total w/ After  : 517
```

With MP:
```
Elapsed Time    : 2.90 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 929
Total w/ After  : 517
```

I wonder if there is something different with the Jan 2017 data? Or maybe the way Windows handles unicode characters vs Mac/Unix?

**Comment by hugovk** [comment]
There could well be some Unicode issue here, as UTF-8 encoding was needed to export to CSV on Windows, so may require handling else where.

Running for 1 hour's worth (Jan 2017) on a Mac with 4 CPU cores also gave the same totals:

Without MP:
```
Elapsed Time    : 1.02 min
Total Tweets    : 121131
Total Matches   : 30
Total w/ Before : 1
Total w/ After  : 0
```

With MP:
```
Elapsed Time    : 0.47 min
Total Tweets    : 121131
Total Matches   : 30
Total w/ Before : 1
Total w/ After  : 0
```

One hour is a bit too small sample size, so I'm downloading the August 2016 data too. It'll take a while, but I'll check what I get with that. (The reason for running on Windows was because I didn't have enough free space on Mac for the full archive!)

**Comment by hugovk** [comment]
On **Windows** with one day of August 2016:

Without MP:
```
Elapsed Time    : 16.14 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 40
Total w/ After  : 0
```

With MP:
```
Elapsed Time    : 6.27 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 40
Total w/ After  : 0
```

Okay, at least MP and non-MP match on Windows.

---

On **Mac** with one day of August 2016:

Without MP:
```
Elapsed Time    : 33.25 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 40
Total w/ After  : 0
```

With MP:
```
Elapsed Time    : 13.30 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 40
Total w/ After  : 0
```

Now this is strange. Again, at least MP and non-MP match, but this the same as Windows and different to what you got. Will dig deeper.

**Comment by hugovk** [comment]
Aha, I know the problem! It is a Unicode thing: I've been using Python 2.7, and this is Python 3 code! Shouldn't be too hard to make Python 2-compatible, but that can wait for another day.

Rerunning one day of August 2016 with **Python 3.6** on Mac:

Without MP:
```
Elapsed Time    : 25.26 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 929
Total w/ After  : 517
```

With MP:
```
Elapsed Time    : 10.40 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 929
Total w/ After  : 517
```

That's more like it!

**Comment by hugovk** [comment]
And for completeness, rerunning one day of August 2016 with **Python 3.5 on Windows**:

Without MP:
```
Elapsed Time    : 13.28 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 929
Total w/ After  : 517
```

With MP:
```
Elapsed Time    : 5.13 min
Total Tweets    : 3770810
Total Matches   : 1615
Total w/ Before : 929
Total w/ After  : 517
```

It matches!

---

(It's probably not worth the effort in supporting Python 2 due to different character widths for emoji depending on "narrow" or "wide" Python builds: https://stackoverflow.com/a/35462951/724176)

**Pull request merged**
